from .info import router as info_router
from .auth import router as auth_router
from .user import router as user_router
from .course import router as course_router
from .selected_course import router as selected_course_router
from .group import router as group_router
from .website_bulletin import router as website_bulletin_router
from .report import router as report_router
from .report_reply import router as report_reply_router
from .course_bulletin import router as course_bulletin_router
from .discussion import router as discussion_router
from .discussion_topic import router as discussion_topic_router
from .discussion_topic_reply import router as discussion_topic_reply_router
from .course_material import router as course_material_router
from .material_info import router as material_info_router
from .assignment import router as assignment_router
from .file import router as file_router
from .subscription import router as subscription_router
from .notification import router as notification_router
