from .auth import router as auth_router
from .info import router as info_router
from .user import router as user_router
from .course import router as course_router
from .selected_course import router as selected_course_router
from .website_bulletin import router as website_bulletin_router
from .website_bulletin_file import router as website_bulletin_file_router
from .course_bulletin import router as course_bulletin_router
from .discussion import router as discussion_router
from .discussion_topic import router as discussion_topic_router
from .discussion_reply import router as discussion_reply_router
from .discussion_topic_file import router as discussion_topic_file_router
