from .auth import router as auth_router
from .info import router as info_router
from .component import router as component_router
from .course import router as course_router
from .course_bulletin import router as course_bulletin_router
from .discussion import router as discussion_router
from .discussion_topic import router as discussion_topic_router
from .file import router as file_router
from .notification import router as notification_router
from .selected_course import router as selected_course_router
from .subscription import router as subscription_router
from .user import router as user_router
from .website_bulletin import router as website_bulletin_router
from .report import router as report_router
